# Generated by Django 3.1.2 on 2020-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='name',
        ),
        migrations.AddField(
            model_name='router',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='mac_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='sap_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
